### ISSUE TITLE
trace.csv removed from experiment output?

### ISSUE THREAD

**Issue by adwaitnd** [HIPS/Spearmint#12]
Hi,
I'm running spearmint on OS X with anaconda. The output of branin.py doesn't generate a trace.csv file are described in the readme. Is this a bug or was something changed from the original Snoek version of spearmint?

**Comment by mgelbart** [comment]
Hi, the original version of Spearmint on Jasper Snoek's github generates trace.csv, but this version does not. In this version the results are saved in a MongoDB database and can be accessed there. Let me know if you have questions about doing that.
