### ISSUE TITLE
Problem installing Spearmint! and testing the branin example!

### ISSUE THREAD

**Issue by Mehrian** [HIPS/Spearmint#14]
Dear all
I'm a new user and trying to install Spearmint package for Bayesian optimization and I have problem using the software. My problem is with the third step that is mentioned in the site:

STEP 3: Running spearmint
1. Start up a MongoDB daemon instance:
mongod --fork --logpath <path/to/logfile\> --dbpath <path/to/dbfolder\>
2. Run spearmint: python main.py \</path/to/experiment/directory\>)

I don't know where is the logpath and dbpath for mongod.....
Would you please help me to install the package and run the branin example!

Thank you in advance,
Best wishes,
Mohammad

**Comment by JasperSnoek** [comment]
Hi Mohammad, the logpath and dbpath are actually things you set yourself.  Mongodb writes text logs to the log file and puts database files into dbpath.

Jasper

**Comment by Mehrian** [comment]
Hi Jasper
Thanks for answering
The problem is that I don't know how to set logpath and dbpath!!
Sorry, It might be a very elementary procedure :) but as I said, I'm a beginner!
thank you in advance,
Mohammad

**Comment by mgelbart** [comment]
Hi Mohammad,

You need to create an empty file and an empty directory. For example, in a UNIX shell,

>> touch logfile
>> mkdir datadir
>> mongod --fork --logpath logfile --dbpath datadir

The first line creates an empty file called "logfile". The second line creates an empty directory called "datadir". The third line starts MongoDB and tells it to store the logs and data in those places.

Mike

**Comment by Mehrian** [comment]
Hi Mike
Thanks!
I'm using windows 8.1
Would you please let me know where to write these lines? In command prompt, I'll be in the following address: C:\Users\Mohammad

Thanks,
Mohammad

**Comment by mgelbart** [comment]
Hi Mohammad,

I have not used Spearmint or MongoDB on Windows. Let's see if someone else with Windows experience can give you some advice.

Mike

**Comment by JasperSnoek** [comment]
Sorry, I have also never tried this.  This may be a reasonable place to start though: http://docs.mongodb.org/manual/tutorial/install-mongodb-on-windows/

**Comment by Mehrian** [comment]
Dear Jasper and Mike!
Thank you so much for your responses!
I installed Ubuntu on my Laptop! and and I don't have problem installing the package!
In this step I execute the command :
mongod --fork --logpath logfile --dbpath datadir
Up to this step every thing is OK and it says:
child process started successfully, parent exiting

Now, when I want to Run spearmint using the command(python main.py) in the directory : Spearmint-master/spearmint

There is an error saying:
ImportError: No module named spearmint.utils.database.mongodb

Do you have any idea about this?
Thank you so much!
Mohammad

**Comment by mgelbart** [comment]
Just to confirm -- did you do the "pip install" (step 3 of the installation instructions)?

**Comment by Mehrian** [comment]
Yes I did it once!

**Comment by Mehrian** [comment]
I'm wondering if I have to do pip install every time?

**Comment by mgelbart** [comment]
Hmm... 
What do you mean by every time?
So what happens if you open python in the terminal and then type "import spearmint"?

**Comment by Mehrian** [comment]
In which directory I have to type?

**Comment by Mehrian** [comment]
Dear Mike
I have another question!
I want to try the Branin.py example, in step 3, I just start the mongoDB and then run the Spearmint!!
So, where is branin.py???

Sorry, If my questions are very elementary! (It is for the first time! :)))
Best Regards,
Mohammad

**Comment by alyato** [comment]
hi @Mehrian I want to use the Spearmint becasue  it was used by the paper 

> Application of Deep Convolutional Neural Networks for
Detecting Extreme Weather in Climate Datasets

Do you give me some advice how to use spearmint? Thanks

**Comment by Holmeyoung** [comment]
hi @Mehrian ,how did you solve the problem 
> There is an error saying:
> ImportError: No module named spearmint.utils.database.mongodb
i have meet the same problem. sad...

**Comment by Holmeyoung** [comment]
hi @Mehrian ,how did you solve the problem

> There is an error saying:
ImportError: No module named spearmint.utils.database.mongodb

i have meet the same problem. sad...
