### ISSUE TITLE
Trying to test an example with spearmint!

### ISSUE THREAD

**Issue by Mehrian** [HIPS/Spearmint#20]
Dear all
I have 3 parameters in my function, so I changed the config.json file as below:
{
    "language"        : "PYTHON",
    "main-file"       : "Neo.py",
    "likelihood"      : "GAUSSIAN",
    "variables" : {
        "x" : {
            "type" : "FLOAT",
            "size" : 1,
            "min"  : 0.0001,
            "max"  : 0.01
        },
        "y" : {
            "type" : "FLOAT",
            "size" : 1,
            "min"  : 0.4,
            "max"  : 0.9
        },
	"z" : {
            "type" : "FLOAT",
            "size" : 1,
            "min"  : 1e-5,
            "max"  : 5e-5
	}
    }
}

I don't know what to write for " "experiment-name""???
Please someone answers my question!! I really need to use this package!
Best Regards,
Mohammad

**Comment by mprat** [comment]
From what I understand, that's just a name that you give it so it's human-readable.
