### ISSUE TITLE
Problems running example files

### ISSUE THREAD

**Issue by Oogi-Bison** [HIPS/Spearmint#22]
Hi,

I was just wondering if anyone encountered this error message? I'm not entirely sure what is going wrong here, but it seems to be a lower level c++ code that is causing the problem?

I got this message when running the example btw. The first 2 points ran without any problems, but the part where it tries to fit a GP over the points seem to be causing the error messages. I tried updating scipy and numpy but it didn't help.

Thanks :)

Looking for python27.dll
Looking for python27.dll
Looking for python27.dll
In file included from C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\scipy\weave\blitz/blitz/array-impl.h:37:0,
                 from C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\scipy\weave\blitz/blitz/array.h:26,
                 from c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:11:
C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\scipy\weave\blitz/blitz/range.h: In member function 'bool blitz::Range::isAscendingContiguous() const':
C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\scipy\weave\blitz/blitz/range.h:120:34: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
         return ((first_ < last_) && (stride_ == 1) || (first_ == last_));
                                  ^
In file included from C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\numpy\core\include/numpy/ndarraytypes.h:1804:0,
                 from C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\numpy\core\include/numpy/ndarrayobject.h:17,
                 from C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\numpy\core\include/numpy/arrayobject.h:4,
                 from c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:23:
C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h: At global scope:
C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h:13:79: note: #pragma message: C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
                          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION")
                                                                               ^
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp: In function 'PyObject* compiled_func(PyObject*, PyObject*)':
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:745:24: error: ambiguous overload for 'operator<' (operand types are 'int' and 'py::object')
         for (int i=0; i<N; i++)
                        ^
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:745:24: note: candidates are:
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:745:24: note: operator<(int, int) <built-in>
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:745:24: note: operator<(int, float) <built-in>
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:745:24: note: operator<(int, double) <built-in>
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:746:26: error: ambiguous overload for 'operator<' (operand types are 'int' and 'py::object')
           for (int j=0; j<M; j++)
                          ^
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:746:26: note: candidates are:
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:746:26: note: operator<(int, int) <built-in>
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:746:26: note: operator<(int, float) <built-in>
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:746:26: note: operator<(int, double) <built-in>
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:747:28: error: ambiguous overload for 'operator<' (operand types are 'int' and 'py::object')
             for (int d=0; d<D; d++)
                            ^
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:747:28: note: candidates are:
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:747:28: note: operator<(int, int) <built-in>
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:747:28: note: operator<(int, float) <built-in>
c:\users\usr\appdata\local\temp\usr\python27_compiled\sc_efe69a3fecba151ef9b75ee9eed626cb290.cpp:747:28: note: operator<(int, double) <built-in>

**Comment by JasperSnoek** [comment]
That's strange.  It seems like python freaks out when it's trying to do
some C++ compilation within a 'weave' call.  (I wrote a particular
bottleneck in C++ to speed things up.)  Can you comment out the following
lines:
https://github.com/HIPS/Spearmint/blob/master/spearmint/kernels/kernel_utils.py#L230-L234

and then un-indent these lines:
https://github.com/HIPS/Spearmint/blob/master/spearmint/kernels/kernel_utils.py#L236-L237

Cheers,

Jasper

**Comment by Oogi-Bison** [comment]
Thanks Jasper, worked like a charm.

**Comment by ppau1** [comment]
I have the same problem. I've followed the suggested solution but the problem persists.
