### ISSUE TITLE
simple_chooser is broken

### ISSUE THREAD

**Issue by mlopezantequera** [HIPS/Spearmint#30]
simple_chooser attempts to retrieve 'normalized_data_dict' from a TaskGroup object. 
(line 255 in simple_chooser.py)
I presume simple_chooser was working only with the simple_task which is now deprecated.

**Comment by kswersky** [comment]
Yes, simple_chooser was designed to handle only the most basic example, but it is subsumed by default_chooser. Deleted it for now since I don't think it's needed.
