### ISSUE TITLE
Simple Case of 1 Optimization Variable

### ISSUE THREAD

**Issue by jmhessel** [HIPS/Spearmint#32]
Hi,

I think things might be broken when you are only trying to optimize over a single variable with dimension 1.

In base_task.py's paramify, data_vector is a float if there is only one optimization variable, rather than a numpy array containing a float, which causes the "Exception('Input to paramify must be a 1-D array.')" to throw. It's solved by putting it in a numpy array as....

if data_vector.ndim != 1:
            data_vector = np.array([data_vector])

**Comment by NamLQ** [comment]
Thanks jmhessel!

**Comment by midak** [comment]
Hello there, totally new to Spearmint here... 

Well, I am having exactly this trouble for 1D optimization, but at work we have not rights to modify Spearmint sources, So I am pretending it is a 2D optimization.. which is quite awful. 

Is there some way how to carry out 1D optimization non-modifying the source??

Thanks
