### ISSUE TITLE
minimize error for joint modeling task

### ISSUE THREAD

**Issue by satarupaguha11** [HIPS/Spearmint#52]
I am trying to use Spearmint to find the optimal hyper-parameters that mimimize the error for a joint modeling task. Since there are two tasks, there are two errors. But I am supposed to return a single scalar from the callable function. I am unable to understand how to make it work. Kindly help

**Comment by JasperSnoek** [comment]
Hi @satarupaguha11, optimizing multiple objectives is a challenging task.  It doesn't really make sense to optimize multiple objectives jointly without some more information.  Most likely, both objectives will not reach their optimum at the same input.  Thus, you have to somehow combine them into one objective that you want to optimize - the simplest way to do this is to assign weights to either objective (e.g. the new objective could be 0.8 * objective_1 + 0.2*objective_2).   If the objectives have different scales, then this can be difficult to specify.  There is a variety of literature on multi-objective optimization but that goes beyond the scope of what this code was designed to do.

**Comment by satarupaguha11** [comment]
Thank you @JasperSnoek for your reply. I will try assigning weights and see how it works out.
