### ISSUE TITLE
Conditionally tune a variable

### ISSUE THREAD

**Issue by mzhai2** [HIPS/Spearmint#54]
Is there a way of setting a variable to be tunable given the enum state of another variable?

**Comment by JasperSnoek** [comment]
Not currently.  That's a great question.  It actually requires some non-trivial changes to the modeling methodology.  We put some effort into investigating the modeling question (see e.g. http://arxiv.org/pdf/1409.4011v1.pdf if you're interested), but I think really finding the best solution to this is still an open research problem.

**Comment by mzhai2** [comment]
That's pretty interesting. For now would you recommend I decouple the variables into different models and tune them separately or is the current setup sufficient, albeit slower than the ideal solution?

**Comment by JasperSnoek** [comment]
A reasonably working hack is to put in a default value for the variables
when they're unobserved (e.g. 0) and/or a categorical variable that
indicates whether or not that variable is observed.  Doing that with many
such conditional variables will make things quite inefficient though.

Jasper

**Comment by mzhai2** [comment]
Thanks, that sounds like what I have been doing but it does explore the variable space even though the variable is set to be unobserved. It would be a bit slow to explore a lot of different topologies for neural networks.
