### ISSUE TITLE
Shall I use PESM or PESC?

### ISSUE THREAD

**Issue by cuihenggang** [HIPS/Spearmint#81]
Hello,

I have been using Spearmint in another codebase (JasperSnoek/spearmint), but Jasper told me that there are some known pathologies with the optimization routine there, and many of those issues that have been addressed in this codebase (our discussion can be found here: https://github.com/JasperSnoek/spearmint/issues/63#issuecomment-246741880). 

I think I should probably try this codebase. I find there are three branches in this repository (master, PESC, and PESM). Could you tell me what's the difference and which one shall I use?

Thank you very much!

**Comment by mgelbart** [comment]
PESM is for multi-objective optimization. Here's the paper: https://arxiv.org/abs/1511.05467

PESC and master both address the same types of problems. PESC contains some newer features than master. Although I recently did a push into PESC and may have broken something (see #80). The code in master has presumably been used by more people, so while less up-to-date I'd think it's more reliable. The exception is that if you have constrains then PESC should be much better than master..
